package edu.kit.wavelength.client.serialization;

import com.google.gwt.user.client.rpc.RemoteService;
import com.google.gwt.user.client.rpc.RemoteServiceRelativePath;

/**
 * This interface provides methods for accessing and manipulating a SQLite database on the server.
 * The database must provide a means of mapping unique ids to serialization Strings.
 * The ids are generated by the database and returned upon creation of a new entry in the database.
 */
@RemoteServiceRelativePath("database")
public interface DatabaseService extends RemoteService {
	/**
	 * Returns serialization belonging to given id if an entry exists,
	 *  else returns {@code null}
	 * @param id unique id
	 * @return serialization belonging to given id
	 */
	String getSerialization(final String id);
	/**
	 * Adds an entry for the given serialization if it is not already in the database and returns
	 *  the assigned id.
	 * @param serialization valid serialization
	 * @return id mapped to given serialization
	 */
	String addEntry(final String serialization);
}
